language: cpp
sudo: required
dist: bionic
addons:
  apt:
    packages:
      - cmake
compiler:
  - clang
  - gcc
script:
  - mkdir build;cd build;cmake ..;make
before_install:
  - if [ $TRAVIS_OS_NAME == linux ]; then git clone https://github.com/zoelabbb/conio.h.git;cd conio.h;sudo cp conio.h /usr/local/include; fi
